---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: alpine

inputs:
- name: git-repo

run:
  path: git-repo/002-basics-of-reading-a-concourse-pipeline/tasks/successful/run.sh
