---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ruby
    tag: 2.3.1-alpine

inputs:
- name: git-repo

run:
  path: git-repo/tasks/flaky/run.rb

params:
  ALWAYS_FAIL: false